//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFE.FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaElectronica
    {
        public int idFacturaElectronica { get; set; }
        public byte[] numeroConsecutivo { get; set; }
        public string numeroClave { get; set; }
        public Nullable<int> idLocal { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string condicionVenta { get; set; }
        public string plazoCredito { get; set; }
        public string medioPago { get; set; }
        public Nullable<double> montoTotal { get; set; }
        public Nullable<double> descuento { get; set; }
        public string naturalezaDescuento { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
