//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFE.FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int idHisorial { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuarioEditor { get; set; }
        public byte[] tablaEditada { get; set; }
    }
}
