//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFE.FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int idInventario { get; set; }
        public string codigoProducto { get; set; }
        public int tipoCodigo { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
        public string unidad { get; set; }
        public double costoCompra { get; set; }
        public double precioVenta { get; set; }
        public int agregarImpuestoVenta { get; set; }
        public int IdUser { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
