//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFE.FrontEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public int idLocal { get; set; }
        public string tipoIdentificacion { get; set; }
        public string nombre { get; set; }
        public string area { get; set; }
        public string faxTelefono { get; set; }
        public string apartadoPostal { get; set; }
        public string web { get; set; }
        public string pais { get; set; }
        public string provincia { get; set; }
        public string email { get; set; }
        public int IdUser { get; set; }
        public string claveCritografica { get; set; }
        public string passwordHacienda { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
