//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFE.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.facturaElectronica = new HashSet<facturaElectronica>();
        }
    
        public int idCliente { get; set; }
        public string tipoDeIdentificacion { get; set; }
        public string identificacion { get; set; }
        public string nombreCompleto { get; set; }
        public string area { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
        public int idUser { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaElectronica> facturaElectronica { get; set; }
    }
}
