//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFE.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int idHisorial { get; set; }
        public System.DateTime fecha { get; set; }
        public string usuarioEditor { get; set; }
        public string tablaEditada { get; set; }
        public string tipoDeMovimiento { get; set; }
        public string descripcionDeMovimiento { get; set; }
    }
}
