//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFE.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int idInventario { get; set; }
        public int IdUser { get; set; }
        public int tipoCodigo { get; set; }
        public string codigoProducto { get; set; }
        public string unidadDeMedida { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
        public double precioUnitario { get; set; }
        public double montoTotal { get; set; }
        public int agregarImpuestoVenta { get; set; }
        public string codigoDeImpuesto { get; set; }
        public double impuestoTarifa { get; set; }
        public double impuestoMonto { get; set; }
        public double montoTotalLinea { get; set; }
        public int estadoDelProducto { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
